# Generated by Django 5.0.6 on 2024-06-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_produto_disponivel_carrinhoproduto_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operacao', models.CharField(choices=[('entrada', 'entrada'), ('saida', 'saida')], max_length=10)),
                ('origem', models.CharField(choices=[('compra', 'compra'), ('venda', 'venda'), ('estorno_carrinho', 'estorno_carrinho')], max_length=20)),
                ('movimentado', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_estoques', to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_colaborador', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrinhoproduto')),
            ],
        ),
    ]
