# Generated by Django 5.0.6 on 2024-06-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movimentoestoque_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='origem_atualizacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='app.produto'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='origem',
            field=models.CharField(choices=[('compra', 'compra'), ('venda', 'venda'), ('entrada_carrinho', 'entrada_carrinho'), ('estorno_carrinho', 'estorno_carrinho')], max_length=20),
        ),
    ]
