# Generated by Django 5.0.6 on 2024-06-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_estoque_origem_atualizacao_estoque_operacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='carrinho',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.CharField(default='teste', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
