# Generated by Django 5.0.6 on 2024-06-03 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_venda_carrinho_venda_produto_venda_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
        ),
    ]
